# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 422)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 541, 71))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(40, 30, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(180, 30, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.OK_button = QtWidgets.QPushButton(Dialog)
        self.OK_button.setEnabled(True)
        self.OK_button.setGeometry(QtCore.QRect(230, 340, 93, 28))
        self.OK_button.setObjectName("OK_button")
        self.listResult = QtWidgets.QListWidget(Dialog)
        self.listResult.setGeometry(QtCore.QRect(20, 100, 541, 192))
        self.listResult.setObjectName("listResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Type"))
        self.radioButton.setText(_translate("Dialog", "Free Scan"))
        self.radioButton_2.setText(_translate("Dialog", "IP Range"))
        self.OK_button.setText(_translate("Dialog", "OK"))
